#!/usr/bin/env php
<?php

/*
 * This file is part of the Symfony CS utility.
 *
 * (c) Carlos Buenosvinos <hi@carlos.io>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

/**
 * @author Carlos Buenosvinos <hi@carlos.io>
 */

// installed via composer?
if (file_exists($pathNameToAutoload = __DIR__ . '/../../autoload.php')) {
    require_once $pathNameToAutoload;
} else {
    require_once __DIR__ . '/vendor/autoload.php';
}

use CarlosIO\Compify\Console\Application;

$application = new Application();
$application->run();
